# Generated by Django 5.0.2 on 2025-02-22 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubPR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('branch_name', models.CharField(max_length=100)),
                ('repository', models.CharField(max_length=200)),
                ('pr_number', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('test_results', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'GitHub PR',
                'verbose_name_plural': 'GitHub PRs',
            },
        ),
        migrations.CreateModel(
            name='PRRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generated_pr', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'PR Request',
                'verbose_name_plural': 'PR Requests',
            },
        ),
    ]
