# Generated by Django 5.0.2 on 2025-02-22 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0003_uploadedfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysisfeedback',
            name='analysis',
        ),
        migrations.RemoveField(
            model_name='analysismetrics',
            name='analysis',
        ),
        migrations.RemoveField(
            model_name='pranalysis',
            name='pull_request',
        ),
        migrations.RemoveField(
            model_name='prcomment',
            name='analysis',
        ),
        migrations.RemoveField(
            model_name='prcomment',
            name='pull_request',
        ),
        migrations.AlterUniqueTogether(
            name='repository',
            unique_together=None,
        ),
        migrations.DeleteModel(
            name='UploadedFile',
        ),
        migrations.AlterModelOptions(
            name='pullrequest',
            options={},
        ),
        migrations.RenameField(
            model_name='pullrequest',
            old_name='url',
            new_name='pr_link',
        ),
        migrations.AlterUniqueTogether(
            name='pullrequest',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='feedback',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='repo_url',
            field=models.URLField(default=234),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pullrequest',
            name='status',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='AnalysisFeedback',
        ),
        migrations.DeleteModel(
            name='AnalysisMetrics',
        ),
        migrations.DeleteModel(
            name='PRAnalysis',
        ),
        migrations.DeleteModel(
            name='PRComment',
        ),
        migrations.RemoveField(
            model_name='pullrequest',
            name='author',
        ),
        migrations.RemoveField(
            model_name='pullrequest',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='pullrequest',
            name='description',
        ),
        migrations.RemoveField(
            model_name='pullrequest',
            name='pr_number',
        ),
        migrations.RemoveField(
            model_name='pullrequest',
            name='repository',
        ),
        migrations.RemoveField(
            model_name='pullrequest',
            name='title',
        ),
        migrations.RemoveField(
            model_name='pullrequest',
            name='updated_at',
        ),
        migrations.DeleteModel(
            name='Repository',
        ),
    ]
